# Generated by Django 4.2.4 on 2023-09-03 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='shipment_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 3, 14, 12, 26, 241870)),
        ),
    ]
