# Generated by Django 4.2.4 on 2023-09-03 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars_management', '0002_alter_car_shipment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='service_organization',
        ),
        migrations.AlterField(
            model_name='car',
            name='shipment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars_management.servicecompany'),
        ),
    ]
