# Generated by Django 4.2.4 on 2023-09-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_management', '0003_remove_maintenance_service_organization_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplaintType',
            new_name='FailureNode',
        ),
    ]
