# Generated by Django 4.2.4 on 2023-09-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_management', '0004_rename_complainttype_failurenode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FailureNode',
            new_name='FailureNodes',
        ),
        migrations.AlterModelTable(
            name='failurenodes',
            table='failure_nodes',
        ),
    ]
