# Generated by Django 4.2.4 on 2023-09-04 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars_management', '0005_rename_failurenode_failurenodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_config',
            field=models.CharField(default='Стандарт', max_length=255, verbose_name='Комплектация и доп. опции'),
        ),
        migrations.AlterField(
            model_name='car',
            name='consignee',
            field=models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='consignee_address',
            field=models.CharField(max_length=255, verbose_name='Адрес грузополучателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_axle_id',
            field=models.CharField(max_length=255, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_axle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.driveaxletype', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_id',
            field=models.CharField(max_length=255, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.enginemodels', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='factory_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.technics', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='car',
            name='shipment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering_axle_id',
            field=models.CharField(max_length=255, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering_axle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.steeringaxletype', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='supply_contract_data',
            field=models.CharField(max_length=255, verbose_name='№ и дата договора поставки'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_id',
            field=models.CharField(max_length=255, verbose_name='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.transmissionmodels', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 17, 53, 10, 462832), verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.maintenancetype', verbose_name='Вид техобслуживания'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='operating_hours',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars_management.servicecompany', verbose_name='Сервисная организация, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 17, 53, 10, 462832), verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_number',
            field=models.CharField(max_length=255, verbose_name='№ заказа-наряда'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_of_failure',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 17, 53, 10, 462832), verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='downtime_hours',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Время простоя техники, час'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='failure_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='failure_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.failurenodes', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='operating_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='restoration_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 17, 53, 10, 462832), verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='restoration_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.restorationmethods', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='used_spare_parts',
            field=models.TextField(blank=True, null=True, verbose_name='Используемые запчасти'),
        ),
    ]
