# Generated by Django 4.2.4 on 2023-09-04 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_management', '0006_alter_car_car_config_alter_car_consignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 17, 55, 38, 350444), verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 17, 55, 38, 350444), verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_of_failure',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 17, 55, 38, 351445), verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='restoration_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 17, 55, 38, 351445), verbose_name='Дата восстановления'),
        ),
    ]
