# Generated by Django 4.2.4 on 2023-09-04 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_management', '0007_alter_maintenance_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 19, 48, 53, 30645), verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 19, 48, 53, 30645), verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_number',
            field=models.CharField(max_length=255, verbose_name='№ заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_of_failure',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 19, 48, 53, 30645), verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='restoration_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 19, 48, 53, 30645), verbose_name='Дата восстановления'),
        ),
    ]
