# Generated by Django 4.2.4 on 2023-09-08 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars_management', '0008_alter_maintenance_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['maintenance_date'], 'verbose_name': 'Техническое обслуживание', 'verbose_name_plural': 'Технические обслуживания'},
        ),
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ['date_of_failure'], 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_of_failure',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='restoration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата восстановления'),
        ),
    ]
